### ISSUE TITLE
Lizenz fehlt

### ISSUE THREAD

**Issue by EmanuelLoos** [gvzdus/PVPrognose#2]
In diesem Repository fehlt noch eine Lizenz, keine Lizenz würde bedeuten "Alle Rechte vorbehalten".

So wie es aussieht, wurde Code verwendet, der unter der GPLv3 lizenziert ist. Wenn das der fall ist muss auch dieses Projekt entweder unter der GPLv3 oder der AGPLv3 lizenziert werden, da die GPLv3 eine Copyleft-Lizenz ist. (Das ist eine gute Sache.)

https://www.gnu.org/licenses/licenses.html
https://www.gnu.org/licenses/gpl-faq.html

**Comment by gvzdus** [comment]
Erledigt! GPLv3 passt, danke für den Vorschlag
